import{a as w,S as v,i as f}from"./assets/vendor-550cebad.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();async function m(e,s){const n="https://pixabay.com",r="/api/",o={key:"42716405-8ee00579c2dae2c7c3ba8a313",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15},i=n+r;return(await w.get(i,{params:o})).data}const l=document.querySelector(".gallery");function P(e){return`<a href="${e.largeImageURL}" class="gallery-card">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy"/>
    
        <ul class="desc">
          <li class="desc-text">Likes<span>${e.likes}</span></li>
          <li class="desc-text">Views<span>${e.views}</span></li>
          <li class="desc-text">Comments<span>${e.comments}</span></li>
          <li class="desc-text">Downloads<span>${e.downloads}</span></li>
        </ul></a>`}function p(e){const s=e.hits.map(r=>P(r)).join("");l.insertAdjacentHTML("beforeend",s);let n=new v(".gallery a",x);n.on("show.simplelightbox"),n.refresh()}const x={captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250},I=document.querySelector("form"),h=document.querySelector(".loader"),d=document.querySelector(".btn-load");let c,a=1,g=0;const E=15;I.addEventListener("submit",q);d.addEventListener("click",M);async function q(e){e.preventDefault(),a=1,l.innerHTML="",c=e.target.elements.search.value.trim(),L();const s=await m(c,a);g=Math.ceil(s.total/E),s.hits.length===0?(u(),y()):(p(s),S()),b(),e.target.reset()}async function M(){a+=1,L();const e=await m(c,a);e.hits.length===0?(u(),y()):(p(e),$(),S()),b()}function y(e){f.error({title:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",titleColor:"#fff",backgroundColor:"#EF4040",titleSize:"16px",titleLineHeight:"1.5",close:!0,icon:""})}function L(){h.classList.remove("is-hidden")}function b(){h.classList.add("is-hidden")}function O(){d.classList.remove("is-hidden")}function u(){d.classList.add("is-hidden")}function S(){a>=g?(u(),B()):O()}function $(){const e=l.firstChild.getBoundingClientRect().height;scrollBy({top:e*3,behavior:"smooth"})}function B(){f.info({message:"We're sorry, but you've reached the end of search results.",position:"center"})}
//# sourceMappingURL=commonHelpers.js.map
